# Puerto del servidor
server.port=8080

# Configuración de la base de datos MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.wu0tbqx.mongodb.net/saberprodb?retryWrites=true&w=majority

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
